### ISSUE TITLE
Implement Multi-Layer Rust Caching Strategy for 60-80% CI Performance Improvement

### ISSUE THREAD

**Issue by wizardsupreme** [deepbrainspace/goodiebag#31]
# Implement Multi-Layer Rust Caching Strategy for 60-80% CI Performance Improvement

## Problem Statement

Our current CI/CD pipeline lacks comprehensive Rust-specific caching, leading to:
- Excessive build times for Rust packages (`claude-code-toolkit`)
- Redundant dependency compilation on every CI run
- Inefficient resource utilization in GitHub Actions
- Poor developer experience with slow feedback loops

### Current State Assessment
**Existing Infrastructure:**
- ✅ NX cache (`.nx/cache`) is cached via GitHub Actions
- ✅ Basic workspace caching (pnpm store, node_modules) implemented
- ✅ Proper Rust package isolation with `{projectRoot}/target` directories
- ✅ Matrix-based CI with affected package detection

**Missing Optimizations:**
- ❌ No Rust-specific dependency caching
- ❌ No incremental build artifact reuse
- ❌ Suboptimal NX cache utilization for Rust workflows

### Reference Implementation Analysis
Based on successful implementation in `/home/nsm/code/deepbrain/dioxus-action`, which demonstrated effective use of:
- GitHub Actions cache for Cargo registry and git dependencies
- Strategic cache key patterns using `Cargo.lock` hashes
- Layered restore keys for progressive cache hits

### Phase 1: Enhanced GitHub Actions Caching (High Impact, Low Risk)

**Extend `.github/actions/setup-workspace/action.yml`** to include Rust-specific cache paths:

```yaml
- name: Cache Rust dependencies
  uses: actions/cache@v4
  with:
    path:  < /dev/null | 
      ~/.cargo/registry
      ~/.cargo/git
      packages/claude-code-toolkit/target
    key: rust-${{ runner.os }}-${{ hashFiles('packages/claude-code-toolkit/Cargo.lock', 'packages/claude-code-toolkit/Cargo.toml') }}
    restore-keys: |
      rust-${{ runner.os }}-${{ hashFiles('packages/claude-code-toolkit/Cargo.lock') }}
      rust-${{ runner.os }}-
```

**Benefits:**
- Cached Cargo registry (~200MB) prevents re-downloading crates
- Git dependencies cache speeds up git-based dependencies
- Target directory caching preserves incremental compilation

### Phase 2: Cargo Chef Integration (High Impact, Medium Complexity)

**Implement dependency-only builds** using cargo-chef pattern:

```yaml
- name: Cache Cargo Chef dependencies
  uses: actions/cache@v4
  with:
    path: |
      ~/.cargo/registry
      ~/.cargo/git
      packages/claude-code-toolkit/target/chef
    key: chef-${{ runner.os }}-${{ hashFiles('packages/claude-code-toolkit/Cargo.lock') }}

- name: Install cargo-chef
  run: cargo install cargo-chef --locked

- name: Prepare dependency recipe
  working-directory: packages/claude-code-toolkit
  run: cargo chef prepare --recipe-path recipe.json

- name: Build dependencies only
  working-directory: packages/claude-code-toolkit
  run: cargo chef cook --release --recipe-path recipe.json --target-dir target/chef
```

**Benefits:**
- Separates dependency compilation from source code changes
- Massive speedup when only source code changes (not dependencies)
- Docker-style layered caching approach

### Phase 3: NX Cache Optimization (Medium Impact, Low Risk)

**Enhanced output definitions** in `packages/claude-code-toolkit/project.json`:

```json
{
  "build": {
    "executor": "@goodiebag/nx-rust:build",
    "dependsOn": ["test"],
    "outputs": [
      "{projectRoot}/target/release/claude-code-toolkit",
      "{projectRoot}/target/release/deps",
      "{projectRoot}/target/release/build"
    ],
    "options": {
      "toolchain": "stable",
      "release": true,
      "target-dir": "{projectRoot}/target"
    }
  }
}
```

**NX-specific Rust caching configuration:**
```json
{
  "targetDefaults": {
    "@goodiebag/nx-rust:build": {
      "cache": true,
      "inputs": [
        "default",
        "{projectRoot}/Cargo.toml",
        "{projectRoot}/Cargo.lock",
        "\!{projectRoot}/target"
      ]
    }
  }
}
```

### Phase 4: CI Pipeline Enhancement (Medium Impact, Low Risk)

**Rust toolchain setup caching:**
```yaml
- name: Cache Rust toolchain
  uses: actions/cache@v4
  with:
    path: |
      ~/.rustup
      ~/.cargo/bin
    key: rust-toolchain-${{ runner.os }}-stable
```

**Parallel dependency installation** with coordination:
```yaml
- name: Setup Rust (cached)
  uses: actions-rs/toolchain@v1
  with:
    profile: minimal
    toolchain: stable
    override: true
```

### Quantitative Targets:
- **60-80% reduction** in Rust build times for unchanged dependencies
- **40-60% reduction** in overall CI duration for Rust packages
- **50-70% reduction** in GitHub Actions minutes consumption
- **Near-instant rebuilds** when only source code changes

### Qualitative Benefits:
- Improved developer experience with faster feedback
- Reduced CI queue times during peak development
- Better resource utilization and cost efficiency
- Enhanced reliability through incremental builds

### Phase 1 (Week 1): GitHub Actions Rust Caching
- **Priority**: High Impact, Low Risk
- **Effort**: 1-2 days
- **Deliverable**: Enhanced setup-workspace action with Rust caching

### Phase 3 (Week 1): NX Output Optimization
- **Priority**: Medium Impact, Low Risk  
- **Effort**: 1 day
- **Deliverable**: Improved NX configuration for Rust builds

### Phase 2 (Week 2): Cargo Chef Integration
- **Priority**: High Impact, Medium Complexity
- **Effort**: 3-4 days
- **Deliverable**: Dependency-only build pipeline

### Phase 4 (Week 3): CI Pipeline Tweaks
- **Priority**: Medium Impact, Low Risk
- **Effort**: 1-2 days
- **Deliverable**: Optimized toolchain and coordination

### Architecture Constraints:
- Must maintain NX workspace isolation (`{projectRoot}/target`)
- Cannot create root-level `target/` directory
- Must work with existing matrix-based CI strategy
- Must preserve affected package detection

### Risk Mitigation:
- Implement phases incrementally with rollback capability
- Monitor cache hit rates and performance metrics
- Maintain compatibility with local development workflows
- Document cache invalidation strategies

### Performance Metrics:
- [ ] CI build time for `claude-code-toolkit` reduced by 60%+ when dependencies unchanged
- [ ] CI build time reduced by 40%+ when only source code changes
- [ ] Cache hit rate >90% for Cargo registry and git dependencies
- [ ] No regression in build reliability or artifact quality

### Implementation Checklist:
- [ ] Phase 1: Enhanced GitHub Actions Rust caching implemented
- [ ] Phase 2: Cargo Chef dependency-only builds working
- [ ] Phase 3: NX cache optimization with proper outputs configured
- [ ] Phase 4: CI pipeline enhanced with toolchain caching
- [ ] Performance benchmarks collected and validated
- [ ] Documentation updated with caching strategy details

## Related References

- **Reference Implementation**: `/home/nsm/code/deepbrain/dioxus-action` (cargo + GitHub cache)
- **Current Architecture**: `packages/claude-code-toolkit/CLAUDE.md` (NX workspace rules)
- **CI Configuration**: `.github/workflows/ci.yml` (matrix strategy)
- **Workspace Setup**: `.github/actions/setup-workspace/action.yml` (current caching)

---

**Priority**: High  
**Complexity**: Medium  
**Expected ROI**: Very High (60-80% performance improvement)

This comprehensive caching strategy will significantly improve our development velocity and CI/CD efficiency while maintaining the architectural integrity of our NX monorepo setup.
